package com.notice.domain.elder;

public enum MedicationType {
    IRON_SUPPLEMENT,
    PAIN_RELIEVER,
    NARCOTIC_PAIN_RELIEVER,
    ANTIDEPRESSANT,
    CALCIUM_CHANNEL_BLOCKER,
    ANTIHISTAMINE,
    ANTICHOLINERGIC,
    ALUMINUM_ANTACID,
    LAXATIVE,
    ANTIBIOTIC,
    METFORMIN,
    MAGNESIUM_SUPPLEMENT,
    DIURETIC,
    THIAZIDE,
    SGLT2_INHIBITOR,
    URINARY_INCONTINENCE_MEDICINE,
    PROSTATE_MEDICINE,
    ACE_INHIBITOR,
    STATIN
}